### ISSUE TITLE
no scroll

### ISSUE THREAD

**Issue by pbsmultimedia** [geedmo/yamm3#31]
Hello!
I have no scroll on fixed nav-bar when the height of the yamm content is greater than the viewport.
It only happens in Chrome Mobile on Sony Xperia, Android 4.0.4
Any ideias?
Thanks!

**Comment by geedmo** [comment]
Hi, I don't have access to such device/os. Anyway, fixed position could be sometimes a bit buggy in some browser.. perhaps you could check if the specific version of your browser has any known issue..
This happens in demo?

**Comment by Bite-Webdevelopment** [comment]
When the content of the YAMM exeeds the viewport and you scroll, the content underneath the menu scrolls and not the content of YAMM but because the YAMM is taking all the space on the screen, you can't see the content underneath it scrolling.

**Comment by namgazoo** [comment]
Ok, now as I've bumbed into this and it was a pretty easy fix here it is. 
As to play with this you would use the affix from bootstrap ;)
It will add the class .affix to the yamm navbar
so I just defined this : 
```
.affix
{
    left:0;
    top: 0;
    width:100%;
    max-height:100vh;
    z-index:1;
}

.affix .navbar-collapse {
	max-height:95vh;
	overflow:auto;
}
```
Basicaly, the yamm nav goes fullwidth, outside of it's container, when it gets to the yamm nav.

**vh is vewport height, so it will adapt to the view port! **

What you have to look at here are the 
**max-height:100vh;** which allow for the navbar to fill the screen but not further,
and targeting only the navbar-collapse **overflow:auto;** allows for scrolling AND keeping the navbar-header visible to collapse the whole thing if necessary.

As for the affix part I've rigged the JS so that the container of this yamm called #mainnav would get a definite height to prevent the jump in the content when the div disappears from the flow : 
I work with an ID to allow for other yamm not to be targeted.
I know I should have done a function.... lazzzyyy!
```
/*---------------- Fixed nav on scroll hack from bootstrap --------------*/
	/*finding the yamm nav container's position to be more flexible in the build */
	var navoffset = $('#mainnav').offset();
	/* defines the height of the container to prevent the jump effect of the container loosing its undefined height */
	var mainnavH = $('#mainnav').height();
	$('#mainnav').height(mainnavH);

	/* The fixed nav fix from bootstrap */
	$('#mainnav .yamm').affix({
      offset: { 
        top: navoffset.top // using the yamm nav position 
      }
}); 
```
I hope it helps someone! ;)

**Comment by geedmo** [comment]
Thanks!
