### ISSUE TITLE
Would be nice if you'll remove bootstrap from bower dependencies

### ISSUE THREAD

**Issue by MechanisM** [geedmo/yamm3#34]
People who using yamm3 already knows that it's for bootstrap.
In my case I'm using bootstrap-stylus and don't wanna install original bootstrap(when it is not really needed)
Will be great if you'll add smth like:
``` stylus
/*!
 * Yamm!3 - Yet another megamenu for Bootstrap 3
 * http://geedmo.github.com/yamm3
 *
 * @geedmo - Licensed under the MIT license
 */

//-----------------------------
//  Yamm Styles
//-----------------------------

.yamm .nav,
.yamm .collapse,
.yamm .dropup,
.yamm .dropdown
  position static

.yamm
  .container
    position relative
  .dropdown-menu
    left auto
  .yamm-content
    padding 20px 30px
  .dropdown
    &.yamm-fw
      .dropdown-menu
        left 0
        right 0
```

into yamm.styl and put in alongside with yamm.less and yamm.css
So yamm.styl could be available via bower

**Comment by MechanisM** [comment]
You might be would like if I'll contribute support of compiling stylus file from css via gulp-stylus and gulp-stylint

**Comment by geedmo** [comment]
Not everyone knows it requires bootstrap, and also since it's only for bootstrap, the dependency is a must and that's a normal pattern on most of bower components.
Regarding to stylus, I'd prefer to leave your post for future references, sass is also an option but due to the small size of this component I think is not a big deal for any project to adapt to other languages.
No matter what is your preprocessor, the "right way" to work should be including the yamm.css and then override any style in your project stylesheets.

**Comment by geedmo** [comment]
Hey @MechanisM just want to let you know I've decided to include your PR.
Thanks for your contribution.

**Comment by jdahdah** [comment]
I'd like to add another vote for removing the bootstrap-LESS dependency. This seems reasonable especially now that the yamm3 master includes Sass and Stylus natively. The fact that it's Bootstrap-only should be perfectly obvious considering it's right in the repository description and the first line of the README. This highlights the need for an "or" dependency declaration in bower, but that's a topic for another day.

On a side note, it would be great to have a new release so we can shrinkwrap it for large projects rather than pulling master. It would be preferable to keep it as a package with the option of upgrading, rather than having to copy it into stylesheets to make sure nothing breaks down the road.

**Comment by jdahdah** [comment]
If anyone else having issues with this: you can add the following to your `.bowerrc`. You'll need bower >= 1.6.3.

```
 {
  "ignoredDependencies": [
    "bootstrap"
  ]
}
```
