### ISSUE TITLE
Works with Bootstrap 4 final

### ISSUE THREAD

**Issue by jpdupont** [geedmo/yamm3#63]
I tested, and Yamm3 works with Bootstrap 4 final.
See https://codepen.io/dujp/pen/eyaMvE
It may be necessary to make some cosmetic adjustments. 
This is an extremely lightweight solution (some lines of CSS) quite effective, compared to some complicated solutions found on the net.

**Comment by adamculpepper** [comment]
Thank you @jpdupont! :)

**Comment by geedmo** [comment]
Sorry for being so lazy here. I'm trying to get some traction and put hands on this.
In the next days I'll be testing and releasing a new version for Bootstrap 4.. My plan is to open a new repo starting from Bootstrap 4 implementation with a structure following the common practices nowadays. I don't want to touch too much the master branch in this repo because I know many people used that branch due the lack of releases.

**Comment by geedmo** [comment]
I've just uploaded a new repo for Bootstrap 4 version. Any feedback is greatly appreciated.
https://github.com/geedmo/yamm
